apiVersion: v1
kind: ConfigMap
metadata:
  name: retail-app-config
  namespace: fss-retail
data:
  MONGODB_URI: mongodb://retail-mongodb:27017/retaildb
  NODE_ENV: production
  PORT: "3130"
  SESSION_SECRET: mysecret123
  MONGO_INITDB_DATABASE: retaildb
