apiVersion: v1
kind: ConfigMap
data:
  MONGODB_URI: mongodb://retail-mongodb:27017/retaildb
  NODE_ENV: production
  PORT: "3130"
  SESSION_SECRET: mysecret123
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"MONGODB_URI":"mongodb://retail-mongodb:27017/retaildb","NODE_ENV":"production","PORT":"3130"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"retail-app-config","namespace":"fss-retail"}}
  creationTimestamp: "2026-06-09T05:24:44Z"
  name: retail-app-config
  namespace: fss-retail
  resourceVersion: "14833"
  uid: 94cd4ec2-8e68-4c4a-b39a-46c302ec6114
